[build]
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/ai"
  to = "/.netlify/functions/ai"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
