[build]
  command = "npm run build"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/ai"
  to = "/.netlify/functions/ai"
  status = 200
  force = true

[[redirects]]
  from = "/invalid-route"
  to = "/410.html"
  status = 410

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
